[build]
  command = "npm run build"
  publish = "starter/dist"  # Update this to match the actual directory where Vite outputs the build artifacts
    base = "starter"  

[build.environment]
  NODE_VERSION = "14"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
